#!/bin/bash -e
# set random hour/minute for security updates (cron-apt)

# random hour: 0-23, minute: 0-59
HOUR=$[ ($RANDOM % 23) ]
MINUTE=$[ ($RANDOM % 59) ]

CMDLINE="test -x /usr/sbin/cron-apt && /usr/sbin/cron-apt"

if [ -e /usr/local/sbin/ubuntu-kernel-remove ]; then
 CMDLINE="$CMDLINE && /usr/local/sbin/ubuntu-kernel-remove -a -s"
fi

cat > /etc/cron.d/cron-apt << EOF
# cron job for cron-apt package
# randomized time to prevent clients from accessing repo at the same time
$MINUTE $HOUR * * * root $CMDLINE

EOF
