#!/bin/bash -e
# remove existing ssh keys and generate new ones
# note: ssh daemon needs to be restarted for changes to take effect

echo "* Regenerating SSH cryptographic keys"

for f in /etc/ssh/*_key{,.pub}; do
 rm -f $f
done

dpkg-reconfigure openssh-server
